### PR TITLE
rely on `evalpoly` instead of hardcoding polynomial evaluation

### LINKED ISSUE #49: [Bug] polynomial evaluation accomplished in a suboptimal manner, sure cause of suboptimal accuracy and suboptimal performance
### Description

In several places in the code, the algorithm to evaluate a univariate real polynomial is the naive algorithm. This is sure to cause inaccuracy and worse performance. Especially in the case of polynomials with higher degree (three and up, for example).

A simple fix is to use the `evalpoly` function that comes with Julia. It happens to use the Horner scheme algorithm, instead of the naive algorithm. PR incoming.

### Package Version

tip

### Julia Version

irrelevant

### Reproduction steps

not necessary, leaving this out

### Relevant log output

```shell

```

### Operating System

_No response_

### PR DESCRIPTION
**Pull request by nsajko**
This change applies the `evalpoly` function from Julia `Base`, avoiding hardcoding the polynomial evaluation algorithm.

In most instances, the chosen polynomial evaluation algorithm was quite suboptimal before this change. This change should thus improve both accuracy and performance.

## Related issues

Fixes #49

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/JuliaAstro/SolarPosition.jl/blob/main/docs/src/contributing.md)
- [x] Tests are passing
- [x] Lint workflow is passing
- [x] Docs were updated and workflow is passing

### CODE REVIEW

**Comment by nsajko** [comment]
@langestefan I see that the JuliaFormatter is causing CI to fail. Which release of the formatter am I supposed to format the code base with?

**Comment by nsajko** [comment]
Reverted a subset of this PR, to avoid any possible numerical accuracy regressions.

Later these changes could be reintroduced without accuracy regressions, if issue #51 were to be tackled simultaneously.

File: src/Positioning/deltat.jl [hunk 1]
```diff
@@ -12,17 +12,33 @@ const DELTAT_TABLE = (
...
+            p = (
+                10583.6,
+                -1014.41,
+                33.78311,
+                -5.952053,
+                -0.1798452,
+                0.022174192,
+                0.0090316521,
+            )
+            evalpoly(u, p)
```
Comment (stevengj) [inline src/Positioning/deltat.jl]: Stylistically, I think it's clearer to do `evalpoly(u, (10583.6, ...))` than to define `p` only to use it once, but tastes vary.

These coefficients also have relatively few digits.  Are you sure you can't use single precision?

Comment (nsajko) [reply src/Positioning/deltat.jl]: (Each coefficient is supposed to be equal before and after this PR.)

File: src/Refraction/hughes.jl [hunk 2]
```diff
@@ -84,14 +84,12 @@ function _refraction(model::HUGHES{T}, elevation_deg::T) where {T<:AbstractFloat
...
         refract = T(58.1) / tan_el - T(0.07) / (tan_el^3) + T(8.6e-5) / (tan_el^5)
     elseif elevation_deg > T(-0.575)
-        refract =
-            elevation_deg * (
-                T(-518.2) +
-                elevation_deg *
-                (T(103.4) + elevation_deg * (T(-12.79) + elevation_deg * T(0.711)))
-            ) + T(1735.0)
+        refract = let p = (1735.0, -518.2, 103.4, -12.79, 0.711), q = map(T, p)
+            elevation_deg * evalpoly(elevation_deg, q)
```
Comment (langestefan) [inline src/Refraction/hughes.jl]:
```suggestion
            evalpoly(elevation_deg, q)
```

This should not be multiplied by `elevation_deg`, that's why the test fails.

**Comment by langestefan** [comment]
Thanks! @nsajko
